apiVersion: v1
kind: Secret
metadata:
  name: nextalk-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-db: {{ .Values.postgres.db | quote }}
  postgres-dsn-nextalk: {{ printf "Host=postgres;Port=5432;Database=%s;Username=%s;Password=%s;SSL Mode=Disable" .Values.postgres.db .Values.postgres.user .Values.postgres.password | quote }}
  postgres-dsn-zitadel: {{ printf "postgres://%s:%s@postgres:5432/zitadel?sslmode=disable" .Values.postgres.user .Values.postgres.password | quote }}
  livekit-api-key: {{ .Values.livekit.apiKey | quote }}
  livekit-secret-key: {{ .Values.livekit.secretKey | quote }}
  zitadel-masterkey: {{ .Values.zitadel.masterkey | quote }}
  grafana-admin-user: {{ .Values.grafana.adminUser | quote }}
  grafana-admin-password: {{ .Values.grafana.adminPassword | quote }}
