---
# Bastion сам в себя не прыгает: подключение напрямую по public_ip.
ansible_host: "{{ public_ip }}"
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null

# worker-1 = NAT gateway — должен форвардить пакеты приватных нод наружу.
ufw_default_forward_policy: accept
