---
# UFW правила для HAProxy ноды.
ufw_extra_rules:
  - { rule: allow, port: '6443', proto: tcp, src: "{{ private_network_cidr }}", comment: 'k3s apiserver proxy' }
  - { rule: allow, port: '9000', proto: tcp, src: "{{ private_network_cidr }}", comment: 'haproxy stats' }
