---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: nextalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.13.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: SERVER_BASEPATH
              value: /monitoring/kibana
            - name: SERVER_REWRITEBASEPATH
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /monitoring/kibana/api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: nextalk
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
