---
- name: restart postgres
  ansible.builtin.systemd:
    name: "postgresql@{{ postgresql_version }}-main"
    state: restarted

- name: reload postgres
  ansible.builtin.systemd:
    name: "postgresql@{{ postgresql_version }}-main"
    state: reloaded

- name: restart postgres-exporter
  ansible.builtin.systemd:
    name: prometheus-postgres-exporter
    state: restarted
